### ISSUE TITLE
bot:nick

### ISSUE THREAD

**Issue by DrivenTick** [vicr123/AstralMod#23]
I think, that if you type bot:nick it would say continue in DMs and there you would type your chosen name, because some dumb people like me just type bot:nick and it shows that your nickname is accepted without even asking me about it...

**Comment by ServerLion** [comment]
YES! I agree!

**Comment by reflectronic** [comment]
Basically resolved in 30e7763 - there's now a cancellation dialog and it tells you what it's about to change it to.
