### ISSUE TITLE
Bot command formatting bug(?)

### ISSUE THREAD

**Issue by ThePixelPolygon** [vicr123/AstralMod#30]
Make bot ignore spaces for commands appearing after the prefix. For example, if you type bot: ping, the command won't run, but bot:ping will run. Please fix this.

**Comment by aren-cllc** [comment]
But why would this need to be fixed? It doesn't seem that important to me...

**Comment by reflectronic** [comment]
Maybe it's not important to @aren-cllc but it's important enough that I fixed it. :)
