### ISSUE TITLE
New thing for the 'mod:deal' command

### ISSUE THREAD

**Issue by OfficialRain** [vicr123/AstralMod#36]
If you type mod:deal, you'd get a new item, "warn", which you can give a reason for a warning, and AstralMod will send the warning, and keep track of it

**Comment by vicr123** [comment]
The old AstralMod was unable to persist changes so this couldn't happen. The new one? Maybe :P

**Comment by OfficialRain** [comment]
Alright, I'll go ahead and leave this open for if you decide to add it (if you do add it of course)

**Comment by reflectronic** [comment]
Implemented in 35a4d36
