### ISSUE TITLE
am:nick request

### ISSUE THREAD

**Issue by ghost** [vicr123/AstralMod#42]
I think that if you do "am:nick" it shouldn't go through. People have made that mistake, ![screen shot 2017-09-16 at 8 12 11 pm](https://user-images.githubusercontent.com/28393214/30517158-eca721d2-9b1b-11e7-8e5b-8690c6575d64.png), and its just annoying to have to then manually fix it. If you wanted a clear command you could do "am:clearnick" maybe? And if you do am:nick it just says "Usage: "am:nick {nickname}""

I mean yeah its a basic mistake, but still. Kind of counter intuitive, IMO

**Comment by reflectronic** [comment]
Basically resolved in 30e7763 - there's now a cancellation dialog and it tells you what it's about to change it to.
