### ISSUE TITLE
Feature request: per-channel spam filter settings

### ISSUE THREAD

**Issue by NetwideRogue** [vicr123/AstralMod#51]
We have a bot spam channel on our server, where people will often run the same command many times in a row, and that's allowed.  There's also an admin-exclusive bot spam channel for when commands might send back private information.  It would be useful to be able to give an exemption to those channels specifically.  Currently, AstralMod isn't allowed to manage messages in either channel, but it still complains about spam, just doesn't delete it.

**Comment by Reflectronic** [comment]
I agree, this feature is very useful and should be implemented

**Comment by vicr123** [comment]
Done in Blueprint. Use `am#block spam` to block spam in a single channel.
