### ISSUE TITLE
theCalculator is broken.

### ISSUE THREAD

**Issue by TheDarkBomber** [vicr123/AstralMod#72]
Mathematical expressions, even those as simple as 1+1, do not calculate, with AstralMod returning an error:

**Internal Error**
AstralMod has run into a problem trying to process that command.
**Details**
spawn ENOMEM

**Comment by vicr123** [comment]
Transient issue. Should be fixed now.

In future, server errors would be better reported by pinging me rather than filing a bug report. Thanks :)

**Comment by TheDarkBomber** [comment]
@vicr123 The issue was fixed, however after five minutes, the same issue had arisen again.

**Comment by vicr123** [comment]
Server is probably just running out of memory, I'll reboot it when I have time.

**Comment by TheDarkBomber** [comment]
Does this mean that the bot stores the results of calculations in memory for as long as the server is running? This should be made to not be the case.

**Comment by vicr123** [comment]
No, I've got more than just the bot running on this server.
